### ISSUE TITLE
I need help how to download the plane.

### ISSUE THREAD

**Issue by ghost** [FGMEMBERS/A320neo#23]
Can someone help me how to download the plane? Always wenn i added the plane when i start the flight it crashes and says fuel truck or something not found. HELP ME PLEASE! make a video or explain

**Comment by legoboyvdlp** [comment]
Did you rename the folder to remove -master?

Also, I highly recommend you get the IDG-A32X which actually has fly by wire and autopilot that work as well as other improvements - see:

github.com/it0uchpods/IDG-A32X


Do NOT get this from FGMEMBERS since their fork of our aircraft is no longer updated.

**Comment by aviation12345** [comment]
I already got it but thanks

Jonathan Redpath <notifications@github.com> schrieb am Di., 2. Apr. 2019,
22:24:

**Comment by aviation12345** [comment]
Oh im sorry for the late response

Rui Gonçalves <pereirarui034@gmail.com> schrieb am Di., 23. Apr. 2019,
18:55:
